FROM flink:1.18.1-scala_2.12-java11

# Installa Python se necessario
RUN apt-get update && apt-get install -y python3 python3-pip

# Copia il tuo codice
COPY pipeline.py /opt/beam/
COPY requirements.txt /opt/beam/

# Installa dipendenze Beam
RUN pip3 install -r /opt/beam/requirements.txt

WORKDIR /opt/beam
