apiVersion: v1
kind: Pod
metadata:
  name: beam-python-job-proc
  namespace: flink
spec:
  restartPolicy: OnFailure
  serviceAccountName: flink
  securityContext:
    runAsUser: 9999
    runAsGroup: 9999
    fsGroup: 9999
  containers:
  - name: beam-job
    image: antoniofurone/beam-flink-hello:latest
    command: ["python3", "/opt/beam/pipeline.py"]
    env:
    - name: FLINK_MASTER
      value: "beam-flink-cluster-rest:8081"
    - name: BEAM_ENV
      value: "PROCESS"
    securityContext:
      allowPrivilegeEscalation: false