---
apiVersion: v1
kind: Namespace
metadata:
  name: flowise
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: flowise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowise-pvc
  namespace: flowise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: flowise
data:
  POSTGRES_DB: "flowise"
  POSTGRES_USER: "flowise"
  POSTGRES_PASSWORD: "flowise123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flowise-config
  namespace: flowise
data:
  DATABASE_TYPE: "postgres"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "flowise"
  DATABASE_USER: "flowise"
  DATABASE_PASSWORD: "flowise123"
  FLOWISE_PORT: "3000"
  FLOWISE_USERNAME: "admin"
  FLOWISE_PASSWORD: "admin123"
  DEBUG: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flowise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U flowise
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U flowise
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: flowise
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowise
  namespace: flowise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowise
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flowise
    spec:
      containers:
      - name: flowise
        image: flowiseai/flowise:latest
        env:
        - name: DATABASE_TYPE
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DATABASE_TYPE
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DATABASE_PASSWORD
        - name: FLOWISE_PORT
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: FLOWISE_PORT
        - name: FLOWISE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: FLOWISE_USERNAME
        - name: FLOWISE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: FLOWISE_PASSWORD
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: flowise-config
              key: DEBUG
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: flowise-storage
          mountPath: /home/node/app/.flowise
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: flowise-storage
        persistentVolumeClaim:
          claimName: flowise-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flowise
  namespace: flowise
spec:
  selector:
    app: flowise
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort
